config/routes.rb
Rails.application.routes.draw do
 devise_for :users, controllers: {
        registrations: 'users/registrations'
}

   resources :users, only: [:show, :index, :edit, :update]

   resources :books, only: [:show, :index, :edit, :update, :create, :destroy]

   get 'home/about' => 'home#about', as: "about"

   root to:'home#top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(current_user.id)
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = @books.user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Post successfully!"
      redirect_to book_path(@book.id)
    else
      @user = User.find(current_user.id)
      @users = User.all
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Update successfully!"
      redirect_to book_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_create_book.html.erb
<div class="sidebar">
  <%= form_for(@book) do |f| %>
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <label class="control-label sr-only">Title</label>
      <%= f.text_field :title, class:"form-control", placeholder:"Title" %>
    </div>
    <div>
      <label class="control-label sr-only">Opinion</label>
      <%= f.text_area :opinion, class:"form-control", placeholder:"Opinion" %>
    </div>
    <%= f.submit "Opinion", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Editing Book</h1>
      <%= form_for(@book) do |f|%>
        <% if @book.errors.any? %>
          <div id="error_explanation">
            <h2><%= @book.errors.count %> 件の error がありました。</h2>
            <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field row">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "col-xs-12 book_title"%>
        </div>
        <div class="field row">
          <label for="book-opinion">Opinion</label>
          <%= f.text_area :body, class: "col-xs-12 book_opinion" %>
        <%= f.submit "Update Book" ,class: "btn btn-lg btn-block btn-base-1 mt-20 btn-primary col-xs-12" %>
      <% end %>
    </div>
  </div>
</div>

<%= link_to "Show", book_path(@book.id) %>
<span>|</span>
<%= link_to "Back", books_path %>

<div class="container">
  <div class="row">
    <div class="col-xs-3 col-xs-offset-9">
      <p>CopyRight Infratop.inc</p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= render "users/list", user:@user, book:@book %>
<div class="col-xs-9">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user_id) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
          <% end %>
        </td>
        <td>
          <%= link_to book.title, book_path(book.id) %>
        </td>
        <td>
          <%= book.body %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-3 col-xs-offset-9">
      <p>CopyRight Infratop.inc</p>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= render 'users/list', user:@user, book:@book  %>

<div class="col-xs-9">
  <h2>Book detail</h2>
  <br>
  <table class="table">
    <tbody>
      <tr>
        <td>
          <%= link_to user_path(@user.id) do %>
            <%= attachment_image_tag @books.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %><br>
            <%= @books.user.name %>
          <% end %>
        </td>
        <td>
          <%= @books.title %>
        </td>
        <td>
          <%= @books.body %>
        </td>
      <% if @books.user.id == current_user.id %>
        <td>
          <%= link_to "Edit", edit_book_path(@books.id), class: "btn-sm btn-success"%>
        </td>
        <td>
          <%= link_to "Delete", book_path(@books.id), method: :delete, "data-confirm" => "本当に消しますか？" , class: "btn-sm btn-danger"%>
        </td>
      <% end %>
      </tr>
    </tbody>
  </table>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-3 col-xs-offset-9">
      <p>CopyRight Infratop.inc</p>
    </div>
  </div>
</div>