config/routes.rb
Rails.application.routes.draw do
 devise_for :users, controllers: {
        registrations: 'users/registrations'
}

   resources :users, only: [:show, :index, :edit, :update]

   resources :books, only: [:show, :index, :edit, :update, :create, :destroy]

   get 'home/about' => 'home#about', as: "about"

   root to:'home#top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-inverse" style="border-radius: 0px;">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span class="navbar-brand", style="font-size:20px;padding-top: 10px;color: white;">Bookers</span>
        </div>
      <div class="collapse navbar-collapse" id="navbar" style="float:right;">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li class="">
              <%= link_to user_path(current_user.id) do %>
                <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home
              <% end %>
            </li>
            <li class="">
              <%= link_to users_path do%>
                <span class="glyphicon glyphicon-user" aria-hidden="true">
                </span> Users
              <% end %>
            </li>
            <li class="">
              <%= link_to books_path do %>
                <span class="glyphicon glyphicon-book" aria-hidden="true">
                </span> Books
              <% end %>
            </li>
            <li class="">
              <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out" aria-hidden="true">
                </span> logout
              <% end %>
            </li>
          <% else %>
            <li class="">
              <%= link_to root_path do %>
              <span class="glyphicon glyphicon-home" aria-hidden="true">
                </span> Home
              <% end %>
            </li>
            <li class="">
              <%= link_to about_path do %>
              <span class="glyphicon glyphicon-link" aria-hidden="true">
                </span> About
              <% end %>
            </li>
            <li class="">
              <%= link_to new_user_registration_path do %>
              <span class="glyphicon glyphicon-edit" aria-hidden="true">
                </span> sign  up
              <% end %>
            </li>
            <li class="">
              <%= link_to user_session_path do %>
              <span class="glyphicon glyphicon-log-in" aria-hidden="true">
                </span> login
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div  class="container" style="width: 750px;margin: 0 auto;padding: 0 15px;">
      <div class="row">
        <% if flash[:notice] %>
          <%= flash[:notice] %>
        <% end %>
      <%= yield %>
      </div>
    </div>
  </body>
</html>